import { Link, useLocation } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import Footer from "@/components/Footer";

const content: Record<string, { title: string; intro: string; sections: [string, string][] }> = {
  "/privacy-policy": { title: "Privacy Policy", intro: "We respect your privacy and explain here how information may be collected and used when you use Urban Delights.", sections: [["Information we collect", "We may collect information you provide when ordering or contacting us, including your name, contact details, delivery address and order information."], ["How we use information", "Information may be used to process orders, provide support, communicate about transactions, improve the website and meet legal obligations."], ["Payments and security", "Payment credentials should be processed by the payment provider used at checkout. We do not intend to store full card or banking credentials on the store unless expressly stated."], ["Cookies", "Essential cookies or similar technologies may be used to keep the website functional, remember preferences and understand usage."]] },
  "/terms-and-conditions": { title: "Terms & Conditions", intro: "These terms govern your use of the Urban Delights website and purchases made through the online store.", sections: [["Orders", "Orders are subject to product availability, price confirmation and successful payment where applicable. We may correct obvious listing or pricing errors."], ["Products", "We aim to keep product information accurate. Food products may naturally vary in colour, texture and appearance."], ["Pricing", "Prices are shown in Indian Rupees unless stated otherwise. Applicable delivery charges or taxes will be communicated where relevant before completion."], ["Website use", "You must not misuse the website, attempt unauthorized access, interfere with its operation or use it for unlawful purposes."]] },
  "/shipping-policy": { title: "Shipping Policy", intro: "We aim to deliver your order safely and promptly. Delivery times depend on destination, availability and the delivery partner.", sections: [["Processing", "Orders are processed after confirmation and successful payment where applicable. Processing may take longer during holidays or high-demand periods."], ["Delivery", "Estimated delivery timelines are communicated where available. Delays may occur because of weather, logistics or circumstances outside our control."], ["Delivery address", "Customers are responsible for providing a complete and accurate address and reachable contact details."], ["Damaged packages", "Please document visible damage and contact customer support promptly with your order details and photographs."]] },
  "/returns-refunds": { title: "Returns, Refunds & Cancellation", intro: "Because our products are food items, returns are handled with additional care and subject to applicable law.", sections: [["Damaged or incorrect orders", "If you receive an incorrect, damaged or materially defective product, contact us promptly with order details and photographs so the issue can be reviewed."], ["Returns", "Opened or used food products are generally not eligible for return for hygiene and food-safety reasons, subject to applicable law."], ["Cancellations", "Request cancellation as early as possible. Once an order has been processed or dispatched, cancellation may no longer be possible."], ["Refunds", "Approved refunds are normally initiated through the original payment method or another permitted method. Provider processing times may vary."]] },
  "/about-us": { title: "About Urban Delights", intro: "Urban Delights is built around a simple idea: everyday food should carry the familiar aromas and flavours that make a meal feel like home.", sections: [["Our approach", "We focus on traditional podis and masalas, thoughtful ingredient selection and balanced recipes for everyday cooking."], ["Small-batch mindset", "Our store experience is designed around freshness, care and consistency."], ["Our promise", "We aim to provide clear product information, dependable service and a straightforward buying experience."]] },
  "/contact-us": { title: "Contact Us", intro: "Need help with an order, product or delivery? We are here to help.", sections: [["Customer support", "When contacting support, please keep your order number, registered contact details and a short description of the issue ready."], ["Order issues", "For damaged, missing or incorrect items, contact support promptly after delivery and include clear photographs where relevant."], ["Business information", "Official business address, customer-care contact details and legal entity information should be added here before public launch."]] },
  "/faq": { title: "Frequently Asked Questions", intro: "Quick answers to common questions about shopping with Urban Delights.", sections: [["How do I choose a pack size?", "Select an available pack size on the product card before adding the item to your basket."], ["Why is a price unavailable?", "A product shows Price unavailable when an enabled selling price has not been configured in Pricing Manager."], ["Can I change my order?", "Contact support as soon as possible. Changes depend on whether the order has already been processed or dispatched."], ["What if my order arrives damaged?", "Keep the packaging, take photographs and contact support promptly with your order details."]] },
};

export default function LegalPage() {
  const { pathname } = useLocation();
  const page = content[pathname] ?? content["/privacy-policy"];
  return <div className="min-h-screen bg-stone-50 text-stone-900 pb-8">
    <header className="border-b border-stone-200 bg-white"><div className="container mx-auto flex h-16 items-center justify-between px-4 sm:px-6"><Link to="/"><img src="/logo.png" alt="Urban Delights" className="h-9 w-auto" /></Link><Button asChild variant="outline" className="rounded-full"><Link to="/"><ArrowLeft className="mr-2 h-4 w-4" /> Back to Home</Link></Button></div></header>
    <main className="container mx-auto max-w-4xl px-4 py-12 sm:px-6 sm:py-16"><p className="text-xs font-bold uppercase tracking-[0.18em] text-orange-700">Urban Delights</p><h1 className="mt-2 text-4xl font-bold tracking-tight sm:text-5xl">{page.title}</h1><p className="mt-4 max-w-3xl text-base leading-7 text-stone-600">{page.intro}</p><div className="mt-10 space-y-5">{page.sections.map(([heading, body]) => <section key={heading} className="rounded-2xl border border-stone-200 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-lg font-bold">{heading}</h2><p className="mt-2 text-sm leading-7 text-stone-600">{body}</p></section>)}</div></main>
    <Footer showTopButton />
  </div>;
}
