import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, CreditCard, LayoutGrid, Save, Settings as SettingsIcon, Sparkles, Truck } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useAuth } from "@/hooks/use-auth";
import { DEFAULT_STORE_SETTINGS, useSaveStoreSettings, useStoreSettings, type StoreSettings } from "@/hooks/useStoreSettings";
import { fetchRecipePricing, type RecipePricing } from "@/services/pricingService";
import ImageUpload from "@/components/admin/ImageUpload";

const Field = ({ label, value, onChange, placeholder = "" }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string }) => (
  <div className="space-y-2"><Label>{label}</Label><Input value={value} placeholder={placeholder} onChange={(e) => onChange(e.target.value)} /></div>
);
const Toggle = ({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) => (
  <label className="flex cursor-pointer items-center justify-between gap-4 rounded-xl border border-slate-200 bg-white p-4">
    <span className="text-sm font-semibold text-slate-800">{label}</span>
    <button type="button" onClick={() => onChange(!value)} aria-pressed={value} className={`relative h-7 w-12 rounded-full transition ${value ? "bg-orange-500" : "bg-slate-300"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition ${value ? "left-6" : "left-1"}`} /></button>
  </label>
);

export default function Settings() {
  const navigate = useNavigate();
  const { session, loading: authLoading } = useAuth();
  const { data, isLoading } = useStoreSettings();
  const saveSettings = useSaveStoreSettings();
  const [form, setForm] = useState<StoreSettings>(DEFAULT_STORE_SETTINGS);
  const [pricing, setPricing] = useState<RecipePricing[]>([]);

  useEffect(() => { if (data) setForm(data); }, [data]);
  useEffect(() => { if (!authLoading && !session) navigate("/login", { replace: true }); }, [authLoading, session, navigate]);
  useEffect(() => { fetchRecipePricing().then(setPricing).catch(() => undefined); }, []);

  const set = <K extends keyof StoreSettings>(key: K, value: StoreSettings[K]) => setForm((current) => ({ ...current, [key]: value }));
  const productNames = useMemo(() => pricing.map((item) => item.recipe_name).filter(Boolean).filter((v, i, a) => a.indexOf(v) === i).sort(), [pricing]);

  const save = async () => {
    if (!form.storeName.trim()) return toast.error("Store name is required");
    if (form.freeShippingAbove < 0 || form.shippingFee < 0) return toast.error("Shipping values cannot be negative");
    await saveSettings.mutateAsync({ ...form, logoUrl: form.logoUrl.trim(), storeName: form.storeName.trim(), businessName: form.businessName.trim(), phone: form.phone.trim(), email: form.email.trim(), address: form.address.trim(), gstNumber: form.gstNumber.trim(), upiId: form.upiId.trim(), upiPayeeName: form.upiPayeeName.trim(), upiQrCodeUrl: form.upiQrCodeUrl.trim(), heroEyebrow: form.heroEyebrow.trim(), heroTitle: form.heroTitle.trim(), heroTitleAccent: form.heroTitleAccent.trim(), heroDescription: form.heroDescription.trim(), heroImageUrl: form.heroImageUrl.trim(), heroPrimaryButtonText: form.heroPrimaryButtonText.trim(), heroSecondaryButtonText: form.heroSecondaryButtonText.trim(), footerCopyright: form.footerCopyright.trim(), featuredProductNames: form.featuredProductNames.filter(Boolean) });
    toast.success("Storefront settings saved");
  };

  if (authLoading || !session || isLoading) return <div className="min-h-screen flex items-center justify-center bg-slate-50 text-slate-500">Loading store settings…</div>;

  return <div className="min-h-screen bg-slate-50 px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-6">
    <div className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><Button variant="outline" size="icon" onClick={() => navigate("/admin")}><ArrowLeft className="h-4 w-4" /></Button><div><div className="flex items-center gap-2"><div className="rounded-xl bg-orange-50 p-2 text-orange-600"><SettingsIcon className="h-5 w-5" /></div><h1 className="text-2xl font-black tracking-tight sm:text-3xl">Visual Store Manager</h1></div><p className="mt-1 text-sm text-slate-500">Control the Home Page & Store without editing frontend code.</p></div></div><div className="flex gap-2"><Button variant="outline" onClick={() => navigate("/?preview=1")}>Preview Store</Button><Button onClick={save} disabled={saveSettings.isPending} className="gap-2 bg-orange-600 hover:bg-orange-700"><Save className="h-4 w-4" />{saveSettings.isPending ? "Saving…" : "Save Changes"}</Button></div></div>

    <Tabs defaultValue="homepage"><TabsList className="grid h-auto grid-cols-2 gap-1 overflow-x-auto bg-white p-2 sm:grid-cols-5 lg:grid-cols-10"><TabsTrigger value="business">Business</TabsTrigger><TabsTrigger value="homepage">Homepage</TabsTrigger><TabsTrigger value="visibility">Visibility</TabsTrigger><TabsTrigger value="featured">Featured</TabsTrigger><TabsTrigger value="categories">Categories</TabsTrigger><TabsTrigger value="benefits">Benefits</TabsTrigger><TabsTrigger value="why">Why Us</TabsTrigger><TabsTrigger value="footer">Footer</TabsTrigger><TabsTrigger value="payments">Payments</TabsTrigger><TabsTrigger value="shipping">Shipping</TabsTrigger></TabsList>
      <TabsContent value="business" className="mt-5"><Card><CardHeader><CardTitle>Business Information</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Field label="Store Name" value={form.storeName} onChange={(v) => set("storeName", v)} /><Field label="Legal / Business Name" value={form.businessName} onChange={(v) => set("businessName", v)} /><div><Label>Phone</Label><Textarea className="mt-2 min-h-24" value={form.phone} onChange={(e) => set("phone", e.target.value)} /></div><div><Label>Email</Label><Textarea className="mt-2 min-h-24" value={form.email} onChange={(e) => set("email", e.target.value)} /></div><div className="sm:col-span-2"><Label>Address</Label><Textarea className="mt-2 min-h-28" value={form.address} onChange={(e) => set("address", e.target.value)} /></div><Field label="GST Number" value={form.gstNumber} onChange={(v) => set("gstNumber", v)} /></CardContent></Card></TabsContent>
      <TabsContent value="homepage" className="mt-5 space-y-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-orange-600" />Hero Section</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Eyebrow" value={form.heroEyebrow} onChange={(v) => set("heroEyebrow", v)} /></div><Field label="Hero Heading" value={form.heroTitle} onChange={(v) => set("heroTitle", v)} /><Field label="Highlighted Heading" value={form.heroTitleAccent} onChange={(v) => set("heroTitleAccent", v)} /><div className="sm:col-span-2"><Label>Description</Label><Textarea className="mt-2 min-h-28" value={form.heroDescription} onChange={(e) => set("heroDescription", e.target.value)} /></div><Field label="Hero Image URL" value={form.heroImageUrl} onChange={(v) => set("heroImageUrl", v)} placeholder="/hero.png or https://…" /><div><Label>Primary Button</Label><Input className="mt-2" value={form.heroPrimaryButtonText} onChange={(e) => set("heroPrimaryButtonText", e.target.value)} /></div><div><Label>Secondary Button</Label><Input className="mt-2" value={form.heroSecondaryButtonText} onChange={(e) => set("heroSecondaryButtonText", e.target.value)} /></div></CardContent></Card></TabsContent>
      <TabsContent value="visibility" className="mt-5"><Card><CardHeader><CardTitle>Home Page Controls</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Toggle label="Show Hero" value={form.showHero} onChange={(v) => set("showHero", v)} /><Toggle label="Show Benefits" value={form.showBenefits} onChange={(v) => set("showBenefits", v)} /><Toggle label="Show Categories" value={form.showCategories} onChange={(v) => set("showCategories", v)} /><Toggle label="Show Featured Products" value={form.showFeatured} onChange={(v) => set("showFeatured", v)} /><Toggle label="Show Why Us" value={form.showWhyUs} onChange={(v) => set("showWhyUs", v)} /><Toggle label="Show Footer Links" value={form.showFooterLinks} onChange={(v) => set("showFooterLinks", v)} /><Toggle label="Show Admin Login" value={form.showAdminLogin} onChange={(v) => set("showAdminLogin", v)} /><Toggle label="Show Basket" value={form.showBasket} onChange={(v) => set("showBasket", v)} /></CardContent></Card></TabsContent>
      <TabsContent value="featured" className="mt-5"><Card><CardHeader><CardTitle>Featured Products</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-slate-500">Enter product names exactly as configured in pricing/products. These are stored in the storefront settings.</p><div className="grid gap-3 sm:grid-cols-2">{Array.from({ length: 8 }).map((_, i) => <select key={i} className="h-10 rounded-md border bg-white px-3 text-sm" value={form.featuredProductNames[i] ?? ""} onChange={(e) => { const next = [...form.featuredProductNames]; next[i] = e.target.value; set("featuredProductNames", next); }}><option value="">Not selected</option>{productNames.map((name) => <option key={name} value={name}>{name}</option>)}</select>)}</div></CardContent></Card></TabsContent>
      <TabsContent value="categories" className="mt-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><LayoutGrid className="h-5 w-5 text-orange-600" />Store Categories</CardTitle></CardHeader><CardContent className="space-y-5"><p className="text-sm text-slate-500">Categories are stored as editable settings. Add or replace category cards here.</p>{form.categories.map((category, i) => <div key={i} className="rounded-2xl border border-slate-200 p-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Title" value={category.title} onChange={(v) => set("categories", form.categories.map((x, j) => j === i ? { ...x, title: v } : x))} /><Field label="Subtitle" value={category.subtitle} onChange={(v) => set("categories", form.categories.map((x, j) => j === i ? { ...x, subtitle: v } : x))} /><Field label="Image URL" value={category.imageUrl} onChange={(v) => set("categories", form.categories.map((x, j) => j === i ? { ...x, imageUrl: v } : x))} /><div><Label>Theme</Label><select className="mt-2 h-10 w-full rounded-md border bg-white px-3 text-sm" value={category.theme} onChange={(e) => set("categories", form.categories.map((x, j) => j === i ? { ...x, theme: e.target.value as any } : x))}><option value="orange">Orange</option><option value="green">Green</option><option value="gold">Gold</option><option value="rose">Rose</option><option value="plum">Plum</option></select></div></div></div>)}</CardContent></Card></TabsContent>
      <TabsContent value="benefits" className="mt-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Truck className="h-5 w-5 text-orange-600" />Benefits Strip</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2">{form.benefits.map((benefit, i) => <div key={i} className="rounded-2xl border p-4"><select className="mb-3 h-10 w-full rounded-md border bg-white px-3 text-sm" value={benefit.icon} onChange={(e) => set("benefits", form.benefits.map((x, j) => j === i ? { ...x, icon: e.target.value as any } : x))}><option value="truck">Delivery</option><option value="shield">Quality</option><option value="leaf">Leaf</option><option value="cart">Cart</option></select><Field label="Title" value={benefit.title} onChange={(v) => set("benefits", form.benefits.map((x, j) => j === i ? { ...x, title: v } : x))} /><div className="mt-3"><Field label="Subtitle" value={benefit.subtitle} onChange={(v) => set("benefits", form.benefits.map((x, j) => j === i ? { ...x, subtitle: v } : x))} /></div></div>)}</CardContent></Card></TabsContent>
      <TabsContent value="why" className="mt-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Check className="h-5 w-5 text-orange-600" />Why Urban Delights</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2">{form.whyUs.map((item, i) => <div key={i} className="rounded-2xl border p-4"><select className="mb-3 h-10 w-full rounded-md border bg-white px-3 text-sm" value={item.icon} onChange={(e) => set("whyUs", form.whyUs.map((x, j) => j === i ? { ...x, icon: e.target.value as any } : x))}><option value="shield">Shield</option><option value="sparkles">Sparkles</option><option value="check">Check</option><option value="cart">Cart</option></select><Field label="Title" value={item.title} onChange={(v) => set("whyUs", form.whyUs.map((x, j) => j === i ? { ...x, title: v } : x))} /><div className="mt-3"><Label>Description</Label><Textarea className="mt-2" value={item.description} onChange={(e) => set("whyUs", form.whyUs.map((x, j) => j === i ? { ...x, description: e.target.value } : x))} /></div></div>)}</CardContent></Card></TabsContent>
      <TabsContent value="footer" className="mt-5"><Card><CardHeader><CardTitle>Footer</CardTitle></CardHeader><CardContent><Field label="Copyright Text" value={form.footerCopyright} onChange={(v) => set("footerCopyright", v)} /><div className="mt-4 space-y-3">{form.footerLinks.map((link, i) => <div key={i} className="grid gap-3 rounded-xl border p-3 sm:grid-cols-[1fr_1fr_auto]"><Input value={link.label} onChange={(e) => set("footerLinks", form.footerLinks.map((x, j) => j === i ? { ...x, label: e.target.value } : x))} /><Input value={link.path} onChange={(e) => set("footerLinks", form.footerLinks.map((x, j) => j === i ? { ...x, path: e.target.value } : x))} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={link.enabled} onChange={(e) => set("footerLinks", form.footerLinks.map((x, j) => j === i ? { ...x, enabled: e.target.checked } : x))} />Visible</label></div>)}</div></CardContent></Card></TabsContent>
      <TabsContent value="payments" className="mt-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><CreditCard className="h-5 w-5 text-orange-600" />Payments</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Field label="UPI ID" value={form.upiId} onChange={(v) => set("upiId", v)} placeholder="yourstore@upi" /><Field label="UPI Payee Name" value={form.upiPayeeName} onChange={(v) => set("upiPayeeName", v)} /><Toggle label="Enable Basket" value={form.showBasket} onChange={(v) => set("showBasket", v)} /><div className="sm:col-span-2"><ImageUpload label="UPI Payment QR Code" value={form.upiQrCodeUrl} onChange={(v) => set("upiQrCodeUrl", v)} folder="payments" hint="Upload the exact UPI QR image customers should scan. It will appear in Checkout when UPI Payment is selected." /></div></CardContent></Card></TabsContent>
      <TabsContent value="shipping" className="mt-5"><Card><CardHeader><CardTitle>Shipping</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><div><Label>Free Shipping Above (₹)</Label><Input className="mt-2" type="number" value={form.freeShippingAbove} onChange={(e) => set("freeShippingAbove", Number(e.target.value))} /></div><div><Label>Shipping Fee (₹)</Label><Input className="mt-2" type="number" value={form.shippingFee} onChange={(e) => set("shippingFee", Number(e.target.value))} /></div></CardContent></Card></TabsContent>
    </Tabs>
  </div></div>;
}
