import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, CreditCard, History, Home, Loader2, MapPin, Minus, Phone, Plus, ShoppingBag, Trash2, UserRound } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import Footer from "@/components/Footer";
import { fetchRecipePricing, type RecipePricing } from "@/services/pricingService";
import { useStoreSettings, type StoreSettings } from "@/hooks/useStoreSettings";
import { supabase } from "@/integrations/supabase/client";
import { useQuery } from "@tanstack/react-query";

type CheckoutItem = { key: string; productName: string; pack: string; quantity: number; price: number; image: string };
const defaultProductImages: Record<string, string> = { "Chicken Masala": "/assets/chicken-masala.jpg", "Garam Masala": "/assets/garam-masala.jpg", "Sambar Podi": "/assets/sambar-powder.jpg", "Rasam Podi": "/assets/rasam-powder.jpg", "Karvepaku Podi": "/assets/karvepaku-podi.jpg", "Kobari Podi": "/assets/kobari-powder.jpg", "Palli Podi": "/assets/palli-podi.jpg", "Putnalu Podi": "/assets/putnalu-podi.jpg", "Idly Podi": "/assets/idly-podi.jpg" };
const normalize = (value: string) => value.toLowerCase().replace(/[^a-z0-9]/g, "");
const findImage = (name: string, settings: StoreSettings) => settings.productMedia.find((item) => normalize(item.name) === normalize(name))?.imageUrl || defaultProductImages[name] || "/placeholder.svg";

const StoreCheckout = () => {
  const navigate = useNavigate();
  const { data: settings = {} as StoreSettings } = useStoreSettings();
  const { data: pricing = [] } = useQuery({ queryKey: ["store-pricing"], queryFn: fetchRecipePricing });
  const [items, setItems] = useState<CheckoutItem[]>([]);
  const [submitting, setSubmitting] = useState(false);
  const [success, setSuccess] = useState<string | null>(null);
  const [form, setForm] = useState({ name: "", phone: "", email: "", address: "", notes: "" });
  const [paymentMethod, setPaymentMethod] = useState<"cod" | "upi">("cod");
  const [transactionId, setTransactionId] = useState("");

  useEffect(() => { try { const raw = sessionStorage.getItem("urban-delights-checkout-cart"); const parsed = raw ? JSON.parse(raw) : []; if (Array.isArray(parsed)) setItems(parsed); } catch { setItems([]); } }, []);
  const pricingLookup = useMemo(() => new Map<string, RecipePricing>(pricing.map((entry) => [`${normalize(entry.recipe_name)}|${normalize(entry.quantity_type)}`, entry])), [pricing]);
  const hydratedItems = useMemo(() => items.map((item) => ({ ...item, price: pricingLookup.get(`${normalize(item.productName)}|${normalize(item.pack)}`)?.price ?? item.price, image: item.image || findImage(item.productName, settings) })), [items, pricingLookup, settings]);
  const subtotal = hydratedItems.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const shipping = subtotal === 0 || subtotal >= Number(settings.freeShippingAbove || 0) ? 0 : Number(settings.shippingFee || 0);
  const total = subtotal + shipping;
  const valid = Boolean(form.name.trim() && form.phone.trim() && form.address.trim() && hydratedItems.length > 0 && (paymentMethod !== "upi" || transactionId.trim()));

  const changeQuantity = (key: string, delta: number) => setItems((current) => current.map((item) => item.key === key ? { ...item, quantity: Math.max(1, item.quantity + delta) } : item));
  const removeItem = (key: string) => setItems((current) => current.filter((item) => item.key !== key));
  const goHome = () => navigate("/?preview=1");

  const submitOrder = async (event: React.FormEvent) => {
    event.preventDefault(); if (!valid || submitting) return; setSubmitting(true);
    try {
      const orderItems = hydratedItems.map((item) => ({ recipe_name: item.productName, quantity_type: item.pack, quantity: item.quantity, amount: item.price * item.quantity }));
      const { data, error } = await supabase.rpc("place_storefront_order" as never, { p_customer_name: form.name.trim(), p_phone_number: form.phone.trim(), p_address: form.address.trim(), p_total_amount: total, p_payment_status: "pending", p_notes: [form.email.trim() ? `Email: ${form.email.trim()}` : "", `Payment Method: ${paymentMethod.toUpperCase()}`, form.notes.trim(), paymentMethod === "upi" && transactionId.trim() ? `UPI Transaction: ${transactionId.trim()}` : ""].filter(Boolean).join(" | ") || null, p_items: orderItems } as never);
      if (error) throw error;
      const orderId = String(data || ""); sessionStorage.removeItem("urban-delights-checkout-cart"); setSuccess(orderId);
    } catch (error: any) { window.alert(error?.message || "Could not place the order. Please try again."); } finally { setSubmitting(false); }
  };

  if (success) return <div className="min-h-screen bg-[#f7f8f4] text-slate-900"><main className="mx-auto flex min-h-[70vh] max-w-3xl items-center px-4 py-12"><Card className="w-full rounded-2xl border-stone-200 p-8 text-center shadow-sm"><CheckCircle2 className="mx-auto h-16 w-16 text-emerald-600" /><h1 className="mt-5 font-serif text-3xl font-bold text-[#2f6b45]">Order Placed Successfully</h1><p className="mt-2 text-stone-500">Your order has been received successfully.</p><div className="mt-5 rounded-xl bg-stone-100 p-4 text-sm">Order ID: <span className="font-mono font-bold">{success.slice(0, 8).toUpperCase()}</span><div className="mt-1">Total: <span className="font-bold">₹{total.toFixed(0)}</span></div></div><div className="mt-6 flex flex-wrap justify-center gap-3"><Button onClick={goHome}><Home className="h-4 w-4" />Back to Home</Button><Button variant="outline" onClick={() => navigate("/?preview=1#products")}><ShoppingBag className="h-4 w-4" />Continue Shopping</Button></div></Card></main><Footer /></div>;

  if (!hydratedItems.length) return <div className="min-h-screen bg-[#f7f8f4] text-slate-900"><header className="mx-auto flex max-w-[1680px] items-center justify-between px-5 py-5 sm:px-8"><button onClick={goHome} className="flex items-center gap-2 text-sm font-medium text-stone-500 hover:text-stone-900"><ArrowLeft className="h-4 w-4" />Back to Store</button><h1 className="font-serif text-4xl font-bold text-[#2f6b45]">Checkout</h1><span className="w-9" /></header><main className="mx-auto max-w-3xl px-4 py-10"><Card className="rounded-2xl border-stone-200 p-10 text-center shadow-sm"><ShoppingBag className="mx-auto h-14 w-14 text-stone-300" /><h2 className="mt-4 font-serif text-2xl font-bold">Your basket is empty</h2><p className="mt-2 text-stone-500">Add products before opening checkout.</p><Button className="mt-6 bg-[#2f6b45] hover:bg-[#255536]" onClick={() => navigate("/?preview=1#products")}><Home className="h-4 w-4" />Back to Store</Button></Card></main><Footer /></div>;

  return <div className="min-h-screen bg-[#f7f8f4] text-slate-900"><header className="mx-auto flex max-w-[1680px] items-center justify-between px-5 py-5 sm:px-8"><h1 className="font-serif text-4xl font-bold tracking-tight text-[#2f6b45] sm:text-5xl">Checkout</h1><button type="button" onClick={goHome} aria-label="Return to store" className="flex h-12 w-12 items-center justify-center rounded-xl border border-stone-200 bg-white text-slate-800 shadow-sm transition hover:bg-stone-50"><History className="h-5 w-5" /></button></header><main className="mx-auto max-w-[1680px] px-5 pb-10 sm:px-8"><form onSubmit={submitOrder} className="grid items-stretch gap-7 lg:grid-cols-3"><Card className="overflow-hidden rounded-2xl border-stone-200 bg-white shadow-sm"><CardHeader className="px-7 pb-4 pt-8"><CardTitle className="font-serif text-2xl font-bold">Order Summary</CardTitle></CardHeader><CardContent className="px-7 pb-8"><div className="space-y-5">{hydratedItems.map((item) => <div key={item.key} className="grid grid-cols-[52px_1fr_auto] gap-3 border-b border-stone-200 pb-5"><img src={item.image} alt={item.productName} className="h-14 w-14 rounded-md object-cover" onError={(event) => { event.currentTarget.src = "/placeholder.svg"; }} /><div className="min-w-0"><p className="truncate text-[15px] font-medium">{item.productName}</p><div className="mt-2 flex items-center gap-2"><button type="button" onClick={() => changeQuantity(item.key, -1)} className="flex h-7 w-7 items-center justify-center rounded-full border border-stone-200 text-stone-700 hover:bg-stone-50"><Minus className="h-3.5 w-3.5" /></button><span className="w-5 text-center text-sm">{item.quantity}</span><button type="button" onClick={() => changeQuantity(item.key, 1)} className="flex h-7 w-7 items-center justify-center rounded-full border border-stone-200 text-stone-700 hover:bg-stone-50"><Plus className="h-3.5 w-3.5" /></button><button type="button" onClick={() => removeItem(item.key)} aria-label={`Remove ${item.productName}`} className="ml-1 text-red-500 hover:text-red-700"><Trash2 className="h-4 w-4" /></button></div></div><div className="pt-1 text-sm font-semibold">₹{(item.price * item.quantity).toFixed(0)}</div></div>)}</div><div className="mt-6 border-t border-stone-200 pt-5"><div className="space-y-3 text-sm"><div className="flex items-center justify-between"><span className="text-stone-500">Subtotal</span><span className="font-medium">₹{subtotal.toFixed(2)}</span></div><div className="flex items-center justify-between"><span className="text-stone-500">Shipping</span><span className="font-medium">{shipping === 0 ? "FREE" : `₹${shipping.toFixed(2)}`}</span></div></div><div className="mt-4 border-t border-stone-200 pt-4"><div className="flex items-center justify-between"><span className="font-serif text-xl font-bold">Total</span><span className="font-serif text-xl font-bold text-[#2f6b45]">₹{total.toFixed(2)}</span></div></div></div></CardContent></Card>

<Card className="rounded-2xl border-stone-200 bg-white shadow-sm"><CardHeader className="px-7 pb-2 pt-8"><CardTitle className="font-serif text-2xl font-bold">Your Details</CardTitle></CardHeader><CardContent className="px-7 pb-8"><div className="space-y-5"><div><Label className="text-sm font-medium">Full Name<span className="text-red-500">*</span></Label><div className="relative mt-2"><Input value={form.name} onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))} placeholder="Enter your name" className="h-12 rounded-xl border-stone-200 bg-[#fbfcf8] pr-11" required /><UserRound className="absolute right-3 top-3.5 h-5 w-5 text-stone-400" /></div></div><div><Label className="text-sm font-medium">Email</Label><Input type="email" value={form.email} onChange={(e) => setForm((f) => ({ ...f, email: e.target.value }))} placeholder="Enter email (optional)" className="mt-2 h-12 rounded-xl border-stone-200 bg-[#fbfcf8]" /></div><div><Label className="text-sm font-medium">Phone Number<span className="text-red-500">*</span></Label><div className="relative mt-2"><Input inputMode="tel" value={form.phone} onChange={(e) => setForm((f) => ({ ...f, phone: e.target.value }))} placeholder="10-digit mobile number" className="h-12 rounded-xl border-stone-200 bg-[#fbfcf8] pr-11" required /><Phone className="absolute right-3 top-3.5 h-5 w-5 text-stone-400" /></div></div><div><Label className="text-sm font-medium">Delivery Address<span className="text-red-500">*</span></Label><div className="relative mt-2"><Textarea value={form.address} onChange={(e) => setForm((f) => ({ ...f, address: e.target.value }))} placeholder="Enter full address" className="min-h-[100px] rounded-xl border-stone-200 bg-[#fbfcf8] pr-11" required /><MapPin className="absolute right-3 top-3.5 h-5 w-5 text-stone-400" /></div></div><div><Label className="text-sm font-medium">Order Notes</Label><Textarea value={form.notes} onChange={(e) => setForm((f) => ({ ...f, notes: e.target.value }))} placeholder="Any special instructions? (optional)" className="min-h-[80px] rounded-xl border-stone-200 bg-[#fbfcf8]" /></div></div></CardContent></Card>

<Card className="rounded-2xl border-stone-200 bg-white shadow-sm"><CardHeader className="px-7 pb-2 pt-8"><CardTitle className="font-serif text-2xl font-bold">Payment</CardTitle></CardHeader><CardContent className="px-7 pb-8"><div className="flex min-h-[390px] flex-col justify-center"><div className="space-y-4"><label className="flex cursor-pointer items-start gap-3 rounded-xl border border-stone-200 p-4"><input type="radio" name="payment" checked={paymentMethod === "cod"} onChange={() => setPaymentMethod("cod")} className="mt-1" /><div><div className="font-semibold">Cash on Delivery</div><div className="text-sm text-stone-500">Pay when your order is delivered.</div></div></label><label className="flex cursor-pointer items-start gap-3 rounded-xl border border-stone-200 p-4"><input type="radio" name="payment" checked={paymentMethod === "upi"} onChange={() => setPaymentMethod("upi")} className="mt-1" /><div><div className="font-semibold">UPI</div><div className="text-sm text-stone-500">Pay to {settings.upiPayeeName || settings.storeName}{settings.upiId ? ` · ${settings.upiId}` : ""} and enter the transaction ID.</div></div></label>{paymentMethod === "upi" && <div><Label>UPI Transaction ID</Label><Input className="mt-2 h-12 rounded-xl border-stone-200 bg-[#fbfcf8]" value={transactionId} onChange={(e) => setTransactionId(e.target.value)} placeholder="Enter transaction reference" required /></div>}<div className="flex items-center gap-2 text-sm text-stone-500"><CreditCard className="h-4 w-4" />Payment preference will be saved with the order.</div></div></div><div className="mt-4 border-t border-stone-200 pt-5"><div className="mb-4 flex items-center justify-between text-sm"><span>Shipping</span><span className="font-semibold">{shipping === 0 ? "FREE" : `₹${shipping.toFixed(0)}`}</span></div><Button type="submit" size="lg" className="h-12 w-full rounded-xl bg-[#2f6b45] text-white hover:bg-[#255536]" disabled={!valid || submitting}>{submitting ? <><Loader2 className="h-4 w-4 animate-spin" />Placing Order...</> : "Place Order"}</Button><p className="mt-3 text-center text-xs text-stone-400">By placing the order, you confirm that the delivery details are correct.</p></div></CardContent></Card></form></main><Footer /></div>;
};

export default StoreCheckout;
