import { useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowLeft, ArrowUp, Check, CreditCard, LayoutGrid, Plus, Save, Settings as SettingsIcon, Trash2, Truck } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useAuth } from "@/hooks/use-auth";
import { DEFAULT_STORE_SETTINGS, useSaveStoreSettings, useStoreSettings, type StoreBenefit, type StoreCategory, type StoreSettings, type StoreWhyUs } from "@/hooks/useStoreSettings";
import { fetchRecipePricing, type RecipePricing } from "@/services/pricingService";

const Field = ({ label, value, onChange, placeholder = "" }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string }) => <div className="space-y-2"><Label>{label}</Label><Input value={value} placeholder={placeholder} onChange={(e) => onChange(e.target.value)} /></div>;
const Toggle = ({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) => <label className="flex cursor-pointer items-center justify-between gap-4 rounded-xl border bg-white p-4"><span className="text-sm font-semibold">{label}</span><button type="button" onClick={() => onChange(!value)} aria-pressed={value} className={`relative h-7 w-12 rounded-full transition ${value ? "bg-orange-500" : "bg-slate-300"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition ${value ? "left-6" : "left-1"}`} /></button></label>;
const move = <T,>(items: T[], index: number, delta: -1 | 1) => { const next = [...items]; const target = index + delta; if (target < 0 || target >= next.length) return next; [next[index], next[target]] = [next[target], next[index]]; return next; };
const iconOptions = ["truck", "shield", "leaf", "cart"] as const;
const whyIconOptions = ["shield", "sparkles", "check", "cart"] as const;
const themes = ["orange", "green", "gold", "rose", "plum"] as const;

export default function StoreManager() {
  const navigate = useNavigate();
  const { session, loading: authLoading } = useAuth();
  const { data, isLoading } = useStoreSettings();
  const saveSettings = useSaveStoreSettings();
  const [form, setForm] = useState<StoreSettings>(DEFAULT_STORE_SETTINGS);
  const [pricing, setPricing] = useState<RecipePricing[]>([]);

  useEffect(() => { if (data) setForm(data); }, [data]);
  useEffect(() => { if (!authLoading && !session) navigate("/login", { replace: true }); }, [authLoading, session, navigate]);
  useEffect(() => { fetchRecipePricing().then(setPricing).catch(() => undefined); }, []);

  const set = <K extends keyof StoreSettings>(key: K, value: StoreSettings[K]) => setForm((current) => ({ ...current, [key]: value }));
  const productNames = useMemo(() => pricing.map((item) => item.recipe_name).filter(Boolean).filter((v, i, a) => a.indexOf(v) === i).sort(), [pricing]);
  const updateCategory = (index: number, patch: Partial<StoreCategory>) => set("categories", form.categories.map((item, i) => i === index ? { ...item, ...patch } : item));
  const updateBenefit = (index: number, patch: Partial<StoreBenefit>) => set("benefits", form.benefits.map((item, i) => i === index ? { ...item, ...patch } : item));
  const updateWhy = (index: number, patch: Partial<StoreWhyUs>) => set("whyUs", form.whyUs.map((item, i) => i === index ? { ...item, ...patch } : item));

  const save = async () => {
    if (!form.storeName.trim()) return toast.error("Store name is required");
    if (form.freeShippingAbove < 0 || form.shippingFee < 0) return toast.error("Shipping values cannot be negative");
    try {
      await saveSettings.mutateAsync({
        ...form,
        storeName: form.storeName.trim(), businessName: form.businessName.trim(), phone: form.phone.trim(), email: form.email.trim(), address: form.address.trim(), gstNumber: form.gstNumber.trim(), upiId: form.upiId.trim(), upiPayeeName: form.upiPayeeName.trim(),
        heroEyebrow: form.heroEyebrow.trim(), heroTitle: form.heroTitle.trim(), heroTitleAccent: form.heroTitleAccent.trim(), heroDescription: form.heroDescription.trim(), heroImageUrl: form.heroImageUrl.trim(), heroPrimaryButtonText: form.heroPrimaryButtonText.trim(), heroSecondaryButtonText: form.heroSecondaryButtonText.trim(), footerCopyright: form.footerCopyright.trim(),
        featuredProductNames: form.featuredProductNames.filter(Boolean), categories: form.categories.filter((item) => item.title.trim()).map((item) => ({ ...item, title: item.title.trim(), subtitle: item.subtitle.trim(), productNames: item.productNames.filter(Boolean) })), benefits: form.benefits.filter((item) => item.title.trim()), whyUs: form.whyUs.filter((item) => item.title.trim()), footerLinks: form.footerLinks.filter((item) => item.label.trim() && item.path.trim()),
        freeShippingAbove: Number(form.freeShippingAbove) || 0, shippingFee: Number(form.shippingFee) || 0,
      });
      toast.success("Storefront settings saved");
    } catch (error: any) { toast.error(error?.message ?? "Could not save storefront settings"); }
  };

  if (authLoading || !session || isLoading) return <div className="min-h-screen flex items-center justify-center bg-slate-50 text-slate-500">Loading store settings…</div>;

  return <div className="min-h-screen bg-slate-50 px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-6">
    <div className="sticky top-2 z-30 flex flex-col gap-4 rounded-2xl border bg-white/95 p-5 shadow-sm backdrop-blur sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><Button variant="outline" size="icon" onClick={() => navigate("/admin")}><ArrowLeft className="h-4 w-4" /></Button><div><div className="flex items-center gap-2"><div className="rounded-xl bg-orange-50 p-2 text-orange-600"><SettingsIcon className="h-5 w-5" /></div><h1 className="text-2xl font-black tracking-tight sm:text-3xl">Visual Store Manager</h1></div><p className="mt-1 text-sm text-slate-500">Manage the complete public storefront from one place. No frontend code required.</p></div></div><div className="flex gap-2"><Button variant="outline" onClick={() => navigate("/")}>Preview Store</Button><Button onClick={save} disabled={saveSettings.isPending} className="gap-2 bg-orange-600 hover:bg-orange-700"><Save className="h-4 w-4" />{saveSettings.isPending ? "Saving…" : "Save Changes"}</Button></div></div>

    <Tabs defaultValue="homepage" className="w-full"><TabsList className="grid h-auto min-w-[900px] grid-cols-10 gap-1 overflow-x-auto bg-white p-2"><TabsTrigger value="business">Business</TabsTrigger><TabsTrigger value="homepage">Homepage</TabsTrigger><TabsTrigger value="visibility">Visibility</TabsTrigger><TabsTrigger value="featured">Featured</TabsTrigger><TabsTrigger value="categories">Categories</TabsTrigger><TabsTrigger value="benefits">Benefits</TabsTrigger><TabsTrigger value="why">Why Us</TabsTrigger><TabsTrigger value="footer">Footer</TabsTrigger><TabsTrigger value="payments">Payments</TabsTrigger><TabsTrigger value="shipping">Shipping</TabsTrigger></TabsList>

      <TabsContent value="business" className="mt-5"><Card><CardHeader><CardTitle>Business Information</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Field label="Store Name" value={form.storeName} onChange={(v) => set("storeName", v)} /><Field label="Legal / Business Name" value={form.businessName} onChange={(v) => set("businessName", v)} /><div><Label>Phone</Label><Textarea className="mt-2 min-h-24" value={form.phone} onChange={(e) => set("phone", e.target.value)} /></div><div><Label>Email</Label><Textarea className="mt-2 min-h-24" value={form.email} onChange={(e) => set("email", e.target.value)} /></div><div className="sm:col-span-2"><Label>Address</Label><Textarea className="mt-2 min-h-28" value={form.address} onChange={(e) => set("address", e.target.value)} /></div><Field label="GST Number" value={form.gstNumber} onChange={(v) => set("gstNumber", v)} /></CardContent></Card></TabsContent>

      <TabsContent value="homepage" className="mt-5"><Card><CardHeader><CardTitle>Hero Section</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Eyebrow" value={form.heroEyebrow} onChange={(v) => set("heroEyebrow", v)} /></div><Field label="Hero Heading" value={form.heroTitle} onChange={(v) => set("heroTitle", v)} /><Field label="Highlighted Heading" value={form.heroTitleAccent} onChange={(v) => set("heroTitleAccent", v)} /><div className="sm:col-span-2"><Label>Description</Label><Textarea className="mt-2 min-h-28" value={form.heroDescription} onChange={(e) => set("heroDescription", e.target.value)} /></div><Field label="Hero Image URL" value={form.heroImageUrl} onChange={(v) => set("heroImageUrl", v)} placeholder="/hero.png or https://…" /><Field label="Primary Button Text" value={form.heroPrimaryButtonText} onChange={(v) => set("heroPrimaryButtonText", v)} /><Field label="Secondary Button Text" value={form.heroSecondaryButtonText} onChange={(v) => set("heroSecondaryButtonText", v)} /></CardContent></Card></TabsContent>

      <TabsContent value="visibility" className="mt-5"><Card><CardHeader><CardTitle>Homepage & Store Visibility</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Toggle label="Hero section" value={form.showHero} onChange={(v) => set("showHero", v)} /><Toggle label="Benefits strip" value={form.showBenefits} onChange={(v) => set("showBenefits", v)} /><Toggle label="Category section" value={form.showCategories} onChange={(v) => set("showCategories", v)} /><Toggle label="Featured products" value={form.showFeatured} onChange={(v) => set("showFeatured", v)} /><Toggle label="Why Us section" value={form.showWhyUs} onChange={(v) => set("showWhyUs", v)} /><Toggle label="Footer navigation" value={form.showFooterLinks} onChange={(v) => set("showFooterLinks", v)} /><Toggle label="Admin Login button" value={form.showAdminLogin} onChange={(v) => set("showAdminLogin", v)} /><Toggle label="Basket / cart" value={form.showBasket} onChange={(v) => set("showBasket", v)} /></CardContent></Card></TabsContent>

      <TabsContent value="featured" className="mt-5"><Card><CardHeader><CardTitle>Featured Products</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-slate-500">Choose which products appear in the Featured section. Product prices and pack sizes continue to come from Pricing Manager.</p><div className="grid gap-3 sm:grid-cols-2">{Array.from({ length: 8 }).map((_, i) => <select key={i} className="h-10 rounded-md border bg-white px-3 text-sm" value={form.featuredProductNames[i] ?? ""} onChange={(e) => { const next = [...form.featuredProductNames]; next[i] = e.target.value; set("featuredProductNames", next); }}><option value="">Not selected</option>{productNames.map((name) => <option key={name} value={name}>{name}</option>)}</select>)}</div></CardContent></Card></TabsContent>

      <TabsContent value="categories" className="mt-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><LayoutGrid className="h-5 w-5 text-orange-600" />Category Manager</CardTitle></CardHeader><CardContent className="space-y-5"><div className="flex justify-end"><Button onClick={() => set("categories", [...form.categories, { title: "New Category", subtitle: "Add a short description", theme: "orange", imageUrl: "/hero.png", productNames: [] }])} className="gap-2 bg-orange-600"><Plus className="h-4 w-4" />Add Category</Button></div>{form.categories.map((category, i) => <div key={`${category.title}-${i}`} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Category {i + 1}</p><h3 className="mt-1 font-bold">{category.title || "Untitled"}</h3></div><div className="flex gap-1"><Button variant="outline" size="icon" disabled={i === 0} onClick={() => set("categories", move(form.categories, i, -1))}><ArrowUp className="h-4 w-4" /></Button><Button variant="outline" size="icon" disabled={i === form.categories.length - 1} onClick={() => set("categories", move(form.categories, i, 1))}><ArrowDown className="h-4 w-4" /></Button><Button variant="ghost" size="icon" className="text-red-600" onClick={() => set("categories", form.categories.filter((_, index) => index !== i))}><Trash2 className="h-4 w-4" /></Button></div></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Title" value={category.title} onChange={(v) => updateCategory(i, { title: v })} /><Field label="Subtitle" value={category.subtitle} onChange={(v) => updateCategory(i, { subtitle: v })} /><Field label="Image URL" value={category.imageUrl} onChange={(v) => updateCategory(i, { imageUrl: v })} /><div><Label>Theme</Label><select className="mt-2 h-10 w-full rounded-md border bg-white px-3 text-sm" value={category.theme} onChange={(e) => updateCategory(i, { theme: e.target.value as StoreCategory["theme"] })}>{themes.map((theme) => <option key={theme} value={theme}>{theme}</option>)}</select></div></div><div className="mt-4"><Label>Products in this category</Label><div className="mt-2 grid max-h-56 gap-2 overflow-y-auto rounded-xl border bg-slate-50 p-3 sm:grid-cols-2">{productNames.map((name) => <label key={name} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={category.productNames.includes(name)} onChange={(e) => updateCategory(i, { productNames: e.target.checked ? [...category.productNames, name] : category.productNames.filter((item) => item !== name) })} />{name}</label>)}</div></div></div>)}</CardContent></Card></TabsContent>

      <TabsContent value="benefits" className="mt-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Truck className="h-5 w-5 text-orange-600" />Benefits Manager</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex justify-end"><Button onClick={() => set("benefits", [...form.benefits, { icon: "truck", title: "New Benefit", subtitle: "Add a subtitle" }])} className="gap-2 bg-orange-600"><Plus className="h-4 w-4" />Add Benefit</Button></div>{form.benefits.map((benefit, i) => <div key={`${benefit.title}-${i}`} className="grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-[160px_1fr_1fr_auto]"><select className="h-10 rounded-md border bg-white px-3 text-sm" value={benefit.icon} onChange={(e) => updateBenefit(i, { icon: e.target.value as StoreBenefit["icon"] })}>{iconOptions.map((icon) => <option key={icon} value={icon}>{icon}</option>)}</select><Input value={benefit.title} placeholder="Title" onChange={(e) => updateBenefit(i, { title: e.target.value })} /><Input value={benefit.subtitle} placeholder="Subtitle" onChange={(e) => updateBenefit(i, { subtitle: e.target.value })} /><Button variant="ghost" size="icon" className="text-red-600" onClick={() => set("benefits", form.benefits.filter((_, index) => index !== i))}><Trash2 className="h-4 w-4" /></Button></div>)}</CardContent></Card></TabsContent>

      <TabsContent value="why" className="mt-5"><Card><CardHeader><CardTitle>Why Us Manager</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex justify-end"><Button onClick={() => set("whyUs", [...form.whyUs, { icon: "check", title: "New Reason", description: "Add a description", theme: "orange" }])} className="gap-2 bg-orange-600"><Plus className="h-4 w-4" />Add Reason</Button></div>{form.whyUs.map((item, i) => <div key={`${item.title}-${i}`} className="rounded-2xl border bg-white p-4"><div className="grid gap-3 sm:grid-cols-3"><select className="h-10 rounded-md border bg-white px-3 text-sm" value={item.icon} onChange={(e) => updateWhy(i, { icon: e.target.value as StoreWhyUs["icon"] })}>{whyIconOptions.map((icon) => <option key={icon} value={icon}>{icon}</option>)}</select><select className="h-10 rounded-md border bg-white px-3 text-sm" value={item.theme} onChange={(e) => updateWhy(i, { theme: e.target.value as StoreWhyUs["theme"] })}>{themes.filter((theme) => theme !== "plum").map((theme) => <option key={theme} value={theme}>{theme}</option>)}</select><div className="flex justify-end"><Button variant="ghost" size="icon" className="text-red-600" onClick={() => set("whyUs", form.whyUs.filter((_, index) => index !== i))}><Trash2 className="h-4 w-4" /></Button></div></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><Input value={item.title} placeholder="Title" onChange={(e) => updateWhy(i, { title: e.target.value })} /><Textarea value={item.description} placeholder="Description" onChange={(e) => updateWhy(i, { description: e.target.value })} /></div></div>)}</CardContent></Card></TabsContent>

      <TabsContent value="footer" className="mt-5"><Card><CardHeader><CardTitle>Footer Manager</CardTitle></CardHeader><CardContent className="space-y-4"><Field label="Copyright Text" value={form.footerCopyright} onChange={(v) => set("footerCopyright", v)} /><div className="flex justify-end"><Button onClick={() => set("footerLinks", [...form.footerLinks, { label: "New Link", path: "/", enabled: true }])} variant="outline" className="gap-2"><Plus className="h-4 w-4" />Add Link</Button></div>{form.footerLinks.map((link, i) => <div key={`${link.label}-${i}`} className="grid gap-3 rounded-xl border bg-white p-3 sm:grid-cols-[1fr_1fr_auto_auto]"><Input value={link.label} onChange={(e) => set("footerLinks", form.footerLinks.map((x, j) => j === i ? { ...x, label: e.target.value } : x))} placeholder="Label" /><Input value={link.path} onChange={(e) => set("footerLinks", form.footerLinks.map((x, j) => j === i ? { ...x, path: e.target.value } : x))} placeholder="/path" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={link.enabled} onChange={(e) => set("footerLinks", form.footerLinks.map((x, j) => j === i ? { ...x, enabled: e.target.checked } : x))} />Visible</label><Button variant="ghost" size="icon" className="text-red-600" onClick={() => set("footerLinks", form.footerLinks.filter((_, index) => index !== i))}><Trash2 className="h-4 w-4" /></Button></div>)}</CardContent></Card></TabsContent>

      <TabsContent value="payments" className="mt-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><CreditCard className="h-5 w-5 text-orange-600" />Payments</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Field label="UPI ID" value={form.upiId} onChange={(v) => set("upiId", v)} placeholder="name@upi" /><Field label="UPI Payee Name" value={form.upiPayeeName} onChange={(v) => set("upiPayeeName", v)} /></CardContent></Card></TabsContent>

      <TabsContent value="shipping" className="mt-5"><Card><CardHeader><CardTitle>Shipping Rules</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><div><Label>Free Shipping Above (₹)</Label><Input className="mt-2" type="number" min="0" value={form.freeShippingAbove} onChange={(e) => set("freeShippingAbove", Number(e.target.value))} /></div><div><Label>Shipping Fee (₹)</Label><Input className="mt-2" type="number" min="0" value={form.shippingFee} onChange={(e) => set("shippingFee", Number(e.target.value))} /></div><div className="sm:col-span-2 rounded-xl bg-orange-50 p-4 text-sm text-orange-900">The public basket automatically uses these values when calculating the estimated shipping charge.</div></CardContent></Card></TabsContent>
    </Tabs>
  </div></div>;
}
