import { useEffect } from "react";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter, Routes, Route, Navigate, useLocation } from "react-router-dom";
import BackendDashboard from "./pages/BackendDashboard";
import NotFound from "./pages/NotFound";
import Auth from "./pages/Auth";
import Store from "./pages/Store";
import LegalPage from "./pages/LegalPage";
import StoreManager from "./pages/StoreManager";
import StoreProductImages from "./pages/StoreProductImages";
import StoreBrandingSync from "./components/StoreBrandingSync";
import { AuthProvider, useAuth } from "@/hooks/use-auth";
const queryClient = new QueryClient();
const ScrollToTop = () => { const { pathname } = useLocation(); useEffect(() => { window.scrollTo({ top: 0, left: 0, behavior: "auto" }); document.documentElement.scrollTop = 0; document.body.scrollTop = 0; }, [pathname]); return null; };
const AdminRoute = ({ children }: { children: React.ReactNode }) => { const { session, loading } = useAuth(); if (loading) return <div className="min-h-screen flex items-center justify-center">Loading...</div>; return session ? <>{children}</> : <Navigate to="/login" replace />; };
const HomeRoute = () => { const { session, loading } = useAuth(); const location = useLocation(); if (loading) return <div className="min-h-screen flex items-center justify-center">Loading...</div>; const preview = new URLSearchParams(location.search).get("preview") === "1"; return session && !preview ? <Navigate to="/admin" replace /> : <Store />; };
const App = () => (<QueryClientProvider client={queryClient}><TooltipProvider><Toaster /><Sonner /><AuthProvider><BrowserRouter><ScrollToTop /><StoreBrandingSync /><Routes><Route path="/" element={<HomeRoute />} /><Route path="/login" element={<Auth />} /><Route path="/auth" element={<Navigate to="/login" replace />} /><Route path="/admin" element={<AdminRoute><BackendDashboard /></AdminRoute>} /><Route path="/admin/settings" element={<AdminRoute><StoreManager /></AdminRoute>} /><Route path="/admin/store-products" element={<AdminRoute><StoreProductImages /></AdminRoute>} /><Route path="/privacy-policy" element={<LegalPage />} /><Route path="/terms-and-conditions" element={<LegalPage />} /><Route path="/shipping-policy" element={<LegalPage />} /><Route path="/returns-refunds" element={<LegalPage />} /><Route path="/about-us" element={<LegalPage />} /><Route path="/contact-us" element={<LegalPage />} /><Route path="/faq" element={<LegalPage />} /><Route path="*" element={<NotFound />} /></Routes></BrowserRouter></AuthProvider></TooltipProvider></QueryClientProvider>);
export default App;
