// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzjrsfrfzjayuvzznhfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6anJzZnJmempheXV2enpuaGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDU0ODcsImV4cCI6MjA2NzM4MTQ4N30.tiMXoIq5pOlNozGnH16g-K5CxlU68VQgKtxL-NAFeHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});